apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-java
  labels:
   app: sample-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-java2
  template:
    metadata:
      labels:
        app: sample-java2
    spec:
      containers:
      - name: sample-java
        image: chenjlsmm/java-demo:9759c44a57fa66c25226ea63328f7a9fd2fbd133
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
